CREATE TABLE IF NOT EXISTS post (
  id TEXT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  published_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP DEFAULT NULL,
  rejected_at TIMESTAMP DEFAULT NULL
);